refactor: modularize docker compose and migration scripts
tazama-lf/Full-Stack-Docker-Tazama pull request #64
Opened 2024-09-09 08:15 UTC by Lenbkr

## What did we change?
Modularize docker compose yaml 
Add Auth/Keycloak

## Why are we doing this?

## How was it tested?
- [ ] Locally
- [ ] Development Environment
- [ ] Not needed, changes very basic
- [ ] Husky successfully run
- [ ] Unit tests passing and Documentation done

2024-09-11 05:55 UTC, JeanPierreNell approved these changes

2024-09-13 09:29 UTC, rtkay123 approved these changes

2024-09-17 07:32 UTC, Justus-at-Tazama requested changes

2024-09-17 07:32 UTC, Justus-at-Tazama commented on .env
> +TMS_PORT=3000
Why are we moving this back to 3000?

2024-09-17 07:32 UTC, Justus-at-Tazama commented on README.md
> +RULE_EXECUTER_BRANCH=main
OK, so sure, the thing we are compiling is the rule executor, but the result is the rule _processor_ and it helps if this is unique if we are also then adding the other rule processors. Why are we rolling back this change?

2024-09-17 07:32 UTC, Justus-at-Tazama commented on README.md
> +TMS_PORT=3000
Ditto - the current postman testing environments for the docker deployment all point to port 5000...

2024-09-17 07:32 UTC, Justus-at-Tazama commented on README.md
> + - The Transaction Monitoring Service API at `<https://localhost:5000>`, where messages will be sent for evaluation. (Port configured in .env file under `TMS_PORT`)
Case in point...

2024-09-17 07:32 UTC, Justus-at-Tazama commented on README.md
>  - rule-901
This is also why I'd prefer the rule-executer branch to reflect the rule processor id and not the rule-executer; it's a bit confusing having the .env branch variable say one thing, and then the docker-compose.yaml saying another...

2024-09-17 10:19 UTC, rtkay123 submitted a review, later dismissed

2024-09-17 10:26 UTC, rtkay123 approved these changes

2024-09-18 07:03 UTC, Justus-at-Tazama approved these changes

2024-09-18 07:03 UTC, merged